- name: create auto scaling group
  hosts: localhost
  connection: local
  vars_files:
     - /home/rajgali83/accesskey
  tasks:
  - name: create auto scaling group
    ec2_asg: 
      aws_access_key: "{{ accesskey }}"
      aws_secret_key: "{{ secretkey }}"
      name: "{{ asg_name }}"
      region: us-west-2
      availability_zones: ['us-west-2a']
      load_balancers: "{{ elb_name }}"
      launch_config_name: "{{ launch_config }}"
      min_size: 1
      max_size: 1
      desired_capacity: 1
      replace_all_instances: yes
      vpc_zone_identifier: ['subnet-41ab480b']
      tags: 
        - type: shiva_web_server
      wait_for_instances: yes
