- name: create elb
  hosts: localhost
  connection: local
  vars_files:
     - /home/rajgali83/accesskey
  tasks:
  - name: creating elb
    ec2_elb_lb: 
      aws_access_key: "{{ accesskey }}"
      aws_secret_key: "{{ secretkey }}"
      name: shivawebelb
      state: present
      region: ap-south-1
      cross_az_load_balancing: yes
      listeners:
        - protocol: http
          load_balancer_port: 80
          instance_port: 80
      tags:
        name: shiva_elb
      security_group_ids: sg-f37afc91
      zones: ap-south-1a
      health_check:
        ping_protocol: http
        ping_port: 80
        ping_path: "/index.html"
        response_timeout: 5
        interval: 30
        unhealthy_threshold: 2
        healthy_threshold: 2
