- name: create ec2 launch config
  hosts: localhost
  connection: local
  tasks:
  - name: ec2 lc create
    ec2_lc:
      name: "{{ launch_config }}"
      image_id: ami-0470e33cd681b2476
      instance_type: t2.micro
      key_name: ec2admin
      security_group: ['default']
      region: ap-south-1
      user_data_path: /root/user_data
