- name: create ec2 launch config
  hosts: localhost
  connection: local
  vars_files:
     - /home/rajgali83/pass
  tasks:
  - name: ec2 lc create
    ec2_lc:
      aws_access_key: "{{ accesskey }}"
      aws_secret_key: "{{ secretkey }}"
      name: "{{ launch_config }}"
      image_id: ami-0470e33cd681b2476
      instance_type: t2.micro
      key_name: ec2admin
      security_groups: ['default']
      region: ap-south-1
      user_data_path: ~/user_data
