- name: create alias record
  hosts: localhost
  connection: local
  vars_files:
     - /home/rajgali83/accesskey
  tasks:
  - name: Get elb facts
    ec2_elb_info:
       aws_access_key: "{{ accesskey }}"
       aws_secret_key: "{{ secretkey }}"
       region: us-west-2
       names: "{{ elb_name }}"
    register: elb_info
  - name: create dns record
    route53:
       aws_access_key: "{{ accesskey }}"
       aws_secret_key: "{{ secretkey }}"
       state: present
       zone: easywebaddress.com
       record: new.easywebaddress.com
       type: A
       value: "{{ elb_info.elbs.0.dns_name }}"
       alias: True
       alias_hosted_zone_id: "{{ elb_info.elbs.0.hosted_zone_id }}"
       overwrite: yes
