- name: create alias record
  hosts: localhost
  connection: local
  vars_files:
     - /home/rajgali83/accesskey
  tasks:
  - name: Get elb facts
    ec2_elb_facts:
       aws_access_key: "{{ accesskey }}"
       aws_secret_key: "{{ secretkey }}"
       region: us-west-2
       names: "{{ elb_name }}"
    register: elb_facts
  - name: create dns record
    route53:
       aws_access_key: "{{ accesskey }}"
       aws_secret_key: "{{ secretkey }}"
       state: present
       privatezone: yes
       zone: shivawebaddress.com
       record: www.shivawebaddress.com
       type: A
       value: "dualstack.{{ elb_facts.elbs.0.dns_name }}"
       alias: True
       alias_hosted_zone_id: "{{ elb_facts.elbs.0.hosted_zone_id }}"
       overwrite: yes
