---
- name: ec2 launcher
  hosts: localhost
  gather_facts: False
  connection: local
  vars_files:
     - /home/rajgali83/accesskey
  tasks:
  - name: launching ec2
    ec2:
      aws_access_key: "{{ accesskey }}"
      aws_secret_key: BARi9WDZ/co4JUns70GX0XFIoSEuiojiOSUTO7iQ
      instance_type: t2.micro
      key_name: ec2admin
      image: ami-0470e33cd681b2476
      region: ap-south-1
      group: default
      count: 1
      vpc_subnet_id: subnet-a43803cc
      wait: yes
      assign_public_ip: yes
