- name: validator
  hosts: localhost
  connection: local
  tasks:
  - name: gather facts
    ec2_elb_facts:
      region: ap-south-1
      names: shivawebelb
    register: elb_facts
    
  - debug:
      msg: "{{ elb_facts.elbs.0.dns_name }}"
  - uri:
      url: http://{{ elb_facts.elbs.0.dns_name }}
      return_content: yes
    register: this
    failed_when: "'Hello from Asg' not in this.content"
