- name: validator
  hosts: localhost
  connection: local
  vars_files:
     - /home/rajgali83/accesskey
  tasks:
  - name: gather facts
    ec2_elb_facts:
      aws_access_key: "{{ accesskey }}"
      aws_secret_key: "{{ secretkey }}"
      region: us-west-2
      names: shivawebelb
    register: elb_facts
    
  - debug:
      msg: "{{ elb_facts.elbs.0.dns_name }}"
  - uri:
      url: http://{{ elb_facts.elbs.0.dns_name }}
      return_content: yes
    register: this
    failed_when: "'Hello from Shiva' not in this.content"
